# Especificamos el lenguaje
language: python
# Especificamos las versiones en las cuales se realizarán los test.
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

# Instalamos las dependencias necesarias mediante el gestor de tareas de travis o mediante la herramienta de construcción
install:
 # Gestor de tareas de travis
 # ---------------------------
 - pip install pipenv
 - pipenv install --three
 - pipenv run pip install -r requirements.txt

 # Herramienta de construcción del proyecto
 # ---------------------------
 #- make install


# Ejecución de los test y test de cobertura mediante el gestor de tareas de travis o mediante la herramienta de construcción
script:
 # Gestor de tareas de travis
 # ---------------------------
 - pipenv run python -m pytest tests/test_estacion.py
 - pipenv run python -m pytest tests/test_bicicletas.py
 - pipenv run python -m pytest tests/test_estacion_rest.py
 - pipenv run python -m pytest --cov=estacion --cov=bicicleta --cov=stationbd --cov=bikebd --cov=estacion_rest tests/


 # Herramienta de construcción del proyecto
 # ---------------------------
 #- make test

#Tras la realización de los test de cobertura enviamos los resultados a codecov.
after_success:
 - codecov
