# Especificamos el lenguaje
language: python
# Especificamos las versiones en las cuales se realizarán los test.
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

# Instalamos las dependencias necesarias para la realización de los test mediante
# la herramienta de construcción
install:
 - make install

# Ejecución de los test y test de cobertura mediante la herramienta de construcción
script:
 make test

#Tras la realización de los test de cobertura enviamos los resultados a codecov.
after_success:
 - codecov
